### ISSUE TITLE
Option to have Empty Object in Schema

### ISSUE THREAD

**Issue by captDaylight** [theadam/node-schema#2]
I'm creating a schema with required fields like so

```
subscriptionCreds = Schema({
    email: {
        'This Field is required': str.isEmail()
    },
    notes: {}
})
```

Notes are required so I'd like to just add an empty object, because I have no other check than that there should be something. Is there any way to do that without having to but isLength(1)?

**Comment by theadam** [comment]
I think this is a great idea. I think it would be nice to support your syntax, and also support the required middleware accepting just a message argument, so:

```
var schema = {
  notes: Field.required("you need notes")
};
```

For those that want custom messages for a required field.  

I won't be around this weekend, but will definitely accept a pull request.  If not I can work on it next week.

**Comment by captDaylight** [comment]
Cool. Also, I like the middleware just accepting a message argument. I'm pretty busy this weekend, but if I get a sec I'll try to work it in. thanks!
