### ISSUE TITLE
why is there no synchronous api?

### ISSUE THREAD

**Issue by wellsjo** [theadam/node-schema#3]
By forcing an async paradigm, consumers of this module are forced to write more code to get around the `Schema.validate().then()...` construct.  The vast majority of schema checks are synchronous (checking stuff like length or matching a regex). 

Schema.validate() could work synchronously with an async option for those few cases that need it.

**Comment by theadam** [comment]
Looking back at it, i think a lot can be rewritten in general.  Not sure if I'd want to give the validate function the ability to return either a promise or another type depending on context.  Is that what you are suggesting?  

Another option would be a new top level class (something like AsyncSchema maybe) that would return a promise, relegating the current 'Schema' to only working on synchronous validations.   I am not sure how I feel about that either.  For this I would have to be pretty convinced I could pull out some common validation logic to use between them somehow, but as it stands the promise stuff is pretty ingrained.  Another issue is that it bloats the API a bit.  With things like async/await coming soon (or now if you use babel) there is much less of an issue with working with promises.

**Comment by wellsjo** [comment]
I see your point and agree after taking a look at the code again.  I made my own simple synchronous version https://github.com/littlstar/json-struct

**Comment by theadam** [comment]
Awesome man, looks good! Im closing this for now.
